import type { Resume } from "@job-search/contracts";
import type { ResumeTheme } from "@job-search/core";

/** Escape Typst markup special characters in plain text. */
export function esc(input: string): string {
  return (input ?? "")
    .replace(/\\/g, "\\\\")
    .replace(/([#$*_`@<>\[\]])/g, "\\$1");
}

function contactLine(resume: Resume): string {
  const parts: string[] = [];
  if (resume.basics.email) parts.push(esc(resume.basics.email));
  if (resume.basics.phone) parts.push(esc(resume.basics.phone));
  const loc = [resume.basics.location.city, resume.basics.location.countryCode]
    .filter(Boolean)
    .join(", ");
  if (loc) parts.push(esc(loc));
  for (const p of resume.basics.profiles) {
    if (p.url) parts.push(esc(p.url));
  }
  return parts.join("  ·  ");
}

function section(title: string, body: string): string {
  if (!body.trim()) return "";
  return `\n#sectionTitle[${esc(title)}]\n${body}\n`;
}

function work(resume: Resume): string {
  return resume.work
    .map((w) => {
      const dates = [w.startDate, w.endDate].filter(Boolean).join(" — ");
      const head = `#entryHead([${esc(w.position)}], [${esc(w.company)}], [${esc(dates)}])`;
      const highlights = w.highlights
        .filter(Boolean)
        .map((h) => `  - ${esc(h)}`)
        .join("\n");
      return `${head}\n${highlights}`;
    })
    .join("\n\n");
}

function skills(resume: Resume): string {
  return resume.skills
    .map((s) => `*${esc(s.name)}:* ${esc(s.keywords.join(", "))}`)
    .join(" \\\n");
}

function projects(resume: Resume): string {
  return resume.projects
    .map((p) => {
      const head = `*${esc(p.name)}*${p.url ? ` — ${esc(p.url)}` : ""}`;
      const desc = p.description ? `\n${esc(p.description)}` : "";
      const highlights = p.highlights
        .filter(Boolean)
        .map((h) => `  - ${esc(h)}`)
        .join("\n");
      return `${head}${desc}${highlights ? `\n${highlights}` : ""}`;
    })
    .join("\n\n");
}

function education(resume: Resume): string {
  return resume.education
    .map((e) => {
      const dates = [e.startDate, e.endDate].filter(Boolean).join(" — ");
      const line = [e.studyType, e.area].filter(Boolean).join(", ");
      return `#entryHead([${esc(e.institution)}], [${esc(line)}], [${esc(dates)}])`;
    })
    .join("\n\n");
}

function languages(resume: Resume): string {
  return resume.languages
    .map((l) => `${esc(l.language)}${l.fluency ? ` (${esc(l.fluency)})` : ""}`)
    .join(", ");
}

export function resumeToTypst(resume: Resume, theme: ResumeTheme): string {
  const header = [
    `#text(size: 18pt, weight: "bold", fill: accent)[${esc(resume.basics.name)}]`,
    resume.basics.label
      ? `\\\n#text(size: 11pt, fill: muted)[${esc(resume.basics.label)}]`
      : "",
    `\\\n#text(size: 9pt, fill: muted)[${contactLine(resume)}]`,
  ].join("");

  return `// Auto-generated by @job-search/resume. Do not edit by hand.
#set page(margin: ${theme.marginCm}cm)
#set text(font: "${theme.fontFamily}", size: ${theme.fontSizePt}pt, fill: rgb("${theme.textColor}"))
#set par(justify: false, leading: ${theme.lineSpacingEm}em)
#let accent = rgb("${theme.accentColor}")
#let muted = rgb("${theme.mutedColor}")
#let sectionTitle(body) = [
  #v(${theme.sectionGapEm}em)
  #text(size: 11pt, weight: "bold", fill: accent)[#upper(body)]
  #line(length: 100%, stroke: 0.5pt + accent)
  #v(0.3em)
]
#let entryHead(role, org, dates) = [
  #grid(columns: (1fr, auto), [*#role* — #org], [#text(fill: muted)[#dates]])
]

${header}

${section("Summary", resume.basics.summary ? esc(resume.basics.summary) : "")}
${section("Experience", work(resume))}
${section("Skills", skills(resume))}
${section("Projects", projects(resume))}
${section("Education", education(resume))}
${section("Languages", languages(resume))}
`;
}
